### ISSUE TITLE
Creates a bunch of sessions

### ISSUE THREAD

**Issue by mother2110** [Chambers82/Prometheus#1]
Great tool but when ran it create crazy amount of sessions.
![image](https://user-images.githubusercontent.com/17184373/87238508-fd0adb00-c3b7-11ea-8209-a87968d2a3ad.png)

**Comment by becrevex** [comment]
Use a netcat listener:

$ nc -lvp 443

**Comment by becrevex** [comment]
hmm... how are you deploying the executable? 

I typically just use a netcat listener for the call back:
$ nv -lvp 443

**Comment by mother2110** [comment]
roger
Thank you
